### PR TITLE
fix --force argument order for ansible 2.9+

### PR DESCRIPTION
**Pull request by spk83**

### CODE REVIEW

**Comment by andrewrothstein** [comment]
Are all the builds failing?

**Comment by spk83** [comment]
yep, while running `ansible-galaxy-local-deps-install` with ansible 2.9

**Comment by spk83** [comment]
@andrewrothstein  please let me know when its tagged and published to pypi, thanks!

**Comment by andrewrothstein** [comment]
published as v0.0.17

**Pull request merged**
